const words = [
  {
    theme: "roller coasters",
    names: [
      "yukon striker",
      "tatsu",
      "batman",
      "scream",
      "joker",
      "superman",
      "wicked cyclone",
      "steel vengeance",
      "formula rossa",
      "top thrill dragster",
      "millenium force",
      "orion",
      "hyperion",
      "copperhead strike",
      "dragonfire",
      "draken",
      "montu",
      "kumba",
      "shiekra",
      "iron gwazi",
      "maxx force",
      "incredible hulk",
      "full throttle",
      "goliath",
      "deja vu",
      "twisted colossus",
      "viper"
    ]
  },
  {
    theme: "sonic characters",
    names: [
      "sonic",
      "tails",
      "shadow",
      "silver",
      "doctor robotnik",
      "amy",
      "metal sonic",
      "big",
      "vector",
      "knuckles",
      "espio",
      "charmy",
      "rouge",
      "chip",
      "werehog",
      "blaze",
      "tikal",
      "chaos",
      "princess elise",
      "chao",
      "zavok",
      "super sonic",
      "wisp",
      "cream",
      "jet",
      "wave",
      "zazz",
      "storm"
    ]
  },
  {
    theme: "computer parts",
    names: [
      "motherboard",
      "central processing unit",
      "graphics processing unit",
      "solid state drive",
      "monitor",
      "keyboard",
      "mouse",
      "random access memory",
      "water cooler",
      "air cooler",
      "hard disk drive",
      "heat sinks"
    ]
  },
  {
    theme: "80's metal/glam bands",
    names: [
      "bon jovi",
      "motley crue",
      "twisted sister",
      "ratt",
      "enuff z nuff",
      "the cult",
      "skid row",
      "cinderella",
      "slaughter",
      "wasp",
      "tesla"
    ]
  },
  {
    theme: "fruits",
    names: [
      "banana",
      "apple",
      "grapes",
      "kiwi",
      "strawberry",
      "raspberry",
      "pear",
      "mango",
      "guava",
      "coconut",
      "pineapple",
      "lemon",
      "lime",
      "kumquat",
      "apricot",
      "blueberry",
      "cherry",
      "nectarine",
      "peach",
      "orange",
      "plum",
      "lychee",
      "blackberry",
      "jujube",
      "cranberry",
      "watermelon",
      "cantelope",
      "tangerine"
    ]
  },
  {
    theme: "dinosaurs",
    names: [
      "ardonyx",
      "bactrosaurus",
      "camelotia",
      "dacentrurus",
      "tyrannosaurus rex",
      "velociraptor",
      "triceratops",
      "stegosaurus",
      "pterodactyl",
      "brontosaurus",
      "theropods",
      "gallimimus",
      "armargasaurus",
      "efraasia",
      "gargoyleosaurus"
    ]
  }
];

export default words;
